{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "relayr-challenge.serviceAccountName" . }}
  labels:
{{ include "relayr-challenge.labels" . | indent 4 }}
{{- end -}}
